# Hi :) Here's the config ~XiaoJibaZhanshi

# Available commands: /marketplace, /sell <price>, /blackmarket, /transactions <player>, /marketplacereload

# You can freely use color codes in gui names, item names, etc.
# If any values are found to be missing/incorrect, the plugin will use its default values.

# Placeholder formats:
# {time-until-refresh} - XX:XX:XX

black-market-options:
  refresh-time-in-minutes: 5 # min 1, max 10080 (a week)
  max-item-amount:
    random: true # if true, will randomly select UP TO (amount) items
    amount: 5 # min 1, no max amount - it will just keep going until it's the same as normal listing amount
  buyer:
    discount-in-percent: 50.0
  seller:
    reimbursement-in-percent: 200.0 # % of the original price, not the discounted one!

marketplace-options:
  max-listings-per-player: 2 # min 1, no max amount. 2 means maximum of 2 listings put up at the same time.

listing-signatures: # What this does is it adds the line on the bottom of listing's lore, just a small touch
  enabled: true
  black-market: "&0&lBLACK MARKET LISTING"
  marketplace: "&8&lMARKETPLACE LISTING"

command-permissions:
  marketplace: "marketplace.view"
  sell: "marketplace.sell"
  blackmarket: "marketplace.blackmarket"
  transactions: "marketplace.history"
  marketplacereload: "marketplace.reload"

guis:

  filler:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
    lore: []
  black-market:
    name: "&0Black Market &7| &c{time-until-refresh} &7until refresh" # Available placeholder(s): {time-until-refresh}
    rows: 3 # min: 2, max: 6
  normal-market:
    name: "&aMarketplace &7| &c{time-until-refresh} &7until refresh" # Available placeholder(s): {time-until-refresh}
    rows: 3 # min: 2, max: 6