name: Marketplace
version: '1'
main: me.xiaojibazhanshi.marketplace.Marketplace
api-version: '1.20'
authors: [ XiaoJibaZhanshi ]
description: A Marketplace plugin :)
commands:
  sell:
    description: Lists the item in players hand in the marketplace for sale.
  marketplace:
    description: Displays a list of all items currently for sale in the marketplace.
  transactions:
    description: Displays the player's transaction history.
  blackmarket:
    description: Psst! You can buy cheap items here!